# The static half of the universal import.
#
# `__init__.py` resolves every name in `__all__` at runtime through PEP 562,
# which no checker can see: without this stub a user script written against
# `from ocp_viewer_core import *` is a wall of "is not defined", and a named
# import binds the `show` submodule for the checker instead of the function.
# This file is what basedpyright, pyright and friends read instead - the
# enums as real re-exports, the functions with the superset signatures the
# runtime resolves to.
#
# Hand-owned. `tests/test_host_resolution.py` holds every signature here
# equal to the runtime's, so drift fails the suite instead of lying in a
# hover. The host-only names carry the signatures of the host that owns them.
#
# Copyright 2026 Bernhard Walter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from .colors import (
    BaseColorMap as BaseColorMap,
)
from .colors import (
    ColorMap as ColorMap,
)
from .colors import (
    web_to_rgb as web_to_rgb,
)
from .config import (
    AnalysisTool as AnalysisTool,
)
from .config import (
    Camera as Camera,
)
from .config import (
    Collapse as Collapse,
)
from .config import (
    Render as Render,
)
from .config import (
    StudioBackground as StudioBackground,
)
from .config import (
    StudioEnvironment as StudioEnvironment,
)
from .config import (
    StudioTextureMapping as StudioTextureMapping,
)
from .config import (
    StudioToneMapping as StudioToneMapping,
)
from .config import (
    UiTab as UiTab,
)

__version__: str

__all__ = [
    "AnalysisTool",
    "BaseColorMap",
    "Camera",
    "Collapse",
    "ColorMap",
    "Render",
    "StudioBackground",
    "StudioEnvironment",
    "StudioTextureMapping",
    "StudioToneMapping",
    "UiTab",
    "__version__",
    "combined_config",
    "get_default",
    "get_defaults",
    "push_object",
    "remove_object",
    "reset_defaults",
    "reset_show",
    "save_screenshot",
    "set_defaults",
    "set_viewer_config",
    "show",
    "show_all",
    "show_clear",
    "show_object",
    "show_objects",
    "status",
    "web_to_rgb",
    "workspace_config",
]

def show(
    *cad_objs,
    names=None,
    colors=None,
    alphas=None,
    modes=None,
    materials=None,
    port=None,
    viewer=None,
    anchor=None,
    cad_width=None,
    height=None,
    pinning=None,
    theme=None,
    progress="-+*c",
    glass=None,
    tools=None,
    tree_width=None,
    axes=None,
    axes0=None,
    grid=None,
    ortho=None,
    transparent=None,
    default_opacity=None,
    black_edges=None,
    orbit_control=None,
    collapse=None,
    explode=None,
    analysis_tool=None,
    tab=None,
    ticks=None,
    center_grid=None,
    grid_font_size=None,
    up=None,
    zoom=None,
    position=None,
    quaternion=None,
    target=None,
    reset_camera=None,
    clip_slider_0=None,
    clip_slider_1=None,
    clip_slider_2=None,
    clip_normal_0=None,
    clip_normal_1=None,
    clip_normal_2=None,
    clip_intersection=None,
    clip_planes=None,
    clip_object_colors=None,
    zebra_count=None,
    zebra_opacity=None,
    zebra_direction=None,
    zebra_color_scheme=None,
    zebra_mapping_mode=None,
    pan_speed=None,
    rotate_speed=None,
    zoom_speed=None,
    deviation=None,
    angular_tolerance=None,
    edge_accuracy=None,
    default_color=None,
    default_edgecolor=None,
    default_facecolor=None,
    default_thickedgecolor=None,
    default_vertexcolor=None,
    ambient_intensity=None,
    direct_intensity=None,
    metalness=None,
    roughness=None,
    render_edges=None,
    render_normals=None,
    render_mates=None,
    render_joints=None,
    show_parent=None,
    show_locals=None,
    show_sketch_local=None,
    helper_scale=None,
    studio_environment=None,
    studio_env_intensity=None,
    studio_env_rotation=None,
    studio_background=None,
    studio_tone_mapping=None,
    studio_exposure=None,
    studio_shadow_intensity=None,
    studio_shadow_softness=None,
    studio_ao_intensity=None,
    studio_texture_mapping=None,
    studio_4k_env_maps=None,
    debug=None,
    timeit=None,
    _force_in_debug=False,
): ...
def show_object(
    obj,
    name=None,
    options=None,
    parent=None,
    clear=False,
    update=False,
    mode=None,
    material=None,
    port=None,
    viewer=None,
    anchor=None,
    cad_width=None,
    height=None,
    pinning=None,
    theme=None,
    progress="-+*c",
    glass=None,
    tools=None,
    tree_width=None,
    axes=None,
    axes0=None,
    grid=None,
    ortho=None,
    transparent=None,
    default_opacity=None,
    black_edges=None,
    orbit_control=None,
    collapse=None,
    explode=None,
    analysis_tool=None,
    tab=None,
    ticks=None,
    center_grid=None,
    grid_font_size=None,
    up=None,
    zoom=None,
    position=None,
    quaternion=None,
    target=None,
    reset_camera=None,
    clip_slider_0=None,
    clip_slider_1=None,
    clip_slider_2=None,
    clip_normal_0=None,
    clip_normal_1=None,
    clip_normal_2=None,
    clip_intersection=None,
    clip_planes=None,
    clip_object_colors=None,
    zebra_count=None,
    zebra_opacity=None,
    zebra_direction=None,
    zebra_color_scheme=None,
    zebra_mapping_mode=None,
    pan_speed=None,
    rotate_speed=None,
    zoom_speed=None,
    deviation=None,
    angular_tolerance=None,
    edge_accuracy=None,
    default_color=None,
    default_facecolor=None,
    default_thickedgecolor=None,
    default_vertexcolor=None,
    default_edgecolor=None,
    ambient_intensity=None,
    metalness=None,
    roughness=None,
    direct_intensity=None,
    render_edges=None,
    render_normals=None,
    render_mates=None,
    render_joints=None,
    show_parent=None,
    show_locals=None,
    show_sketch_local=None,
    helper_scale=None,
    studio_environment=None,
    studio_env_intensity=None,
    studio_env_rotation=None,
    studio_background=None,
    studio_tone_mapping=None,
    studio_exposure=None,
    studio_shadow_intensity=None,
    studio_shadow_softness=None,
    studio_ao_intensity=None,
    studio_texture_mapping=None,
    studio_4k_env_maps=None,
    debug=None,
    timeit=None,
): ...
def show_objects(
    modes=None,
    port=None,
    viewer=None,
    anchor=None,
    cad_width=None,
    height=None,
    pinning=None,
    theme=None,
    progress="-+*c",
    glass=None,
    tools=None,
    tree_width=None,
    axes=None,
    axes0=None,
    grid=None,
    ortho=None,
    transparent=None,
    default_opacity=None,
    black_edges=None,
    orbit_control=None,
    collapse=None,
    explode=None,
    analysis_tool=None,
    tab=None,
    ticks=None,
    center_grid=None,
    grid_font_size=None,
    up=None,
    zoom=None,
    position=None,
    quaternion=None,
    target=None,
    reset_camera=None,
    clip_slider_0=None,
    clip_slider_1=None,
    clip_slider_2=None,
    clip_normal_0=None,
    clip_normal_1=None,
    clip_normal_2=None,
    clip_intersection=None,
    clip_planes=None,
    clip_object_colors=None,
    zebra_count=None,
    zebra_opacity=None,
    zebra_direction=None,
    zebra_color_scheme=None,
    zebra_mapping_mode=None,
    pan_speed=None,
    rotate_speed=None,
    zoom_speed=None,
    deviation=None,
    angular_tolerance=None,
    edge_accuracy=None,
    default_color=None,
    default_facecolor=None,
    default_thickedgecolor=None,
    default_vertexcolor=None,
    default_edgecolor=None,
    ambient_intensity=None,
    metalness=None,
    roughness=None,
    direct_intensity=None,
    render_edges=None,
    render_normals=None,
    render_mates=None,
    render_joints=None,
    show_parent=None,
    show_locals=None,
    show_sketch_local=None,
    helper_scale=None,
    studio_environment=None,
    studio_env_intensity=None,
    studio_env_rotation=None,
    studio_background=None,
    studio_tone_mapping=None,
    studio_exposure=None,
    studio_shadow_intensity=None,
    studio_shadow_softness=None,
    studio_ao_intensity=None,
    studio_texture_mapping=None,
    studio_4k_env_maps=None,
    debug=None,
    timeit=None,
): ...
def show_all(
    variables=None,
    exclude=None,
    classes=None,
    include=None,
    _visual_debug=False,
    **kwargs,
): ...
def show_clear(): ...
def reset_show(): ...
def save_screenshot(
    filename,
    port=None,
    polling=True,
    progress_only=False,
): ...
def push_object(
    obj,
    name=None,
    color=None,
    alpha=None,
    material=None,
    mode=None,
    clear=False,
    update=False,
): ...
def remove_object(
    name,
    call_show=False,
    port=None,
    progress="-+*c",
): ...
def set_defaults(
    glass=None,
    tools=None,
    tree_width=None,
    axes=None,
    axes0=None,
    grid=None,
    ortho=None,
    transparent=None,
    default_opacity=None,
    black_edges=None,
    orbit_control=None,
    theme=None,
    collapse=None,
    ticks=None,
    center_grid=None,
    grid_font_size=None,
    up=None,
    explode=None,
    analysis_tool=None,
    tab=None,
    zoom=None,
    reset_camera=None,
    clip_slider_0=None,
    clip_slider_1=None,
    clip_slider_2=None,
    clip_normal_0=None,
    clip_normal_1=None,
    clip_normal_2=None,
    clip_intersection=None,
    clip_planes=None,
    clip_object_colors=None,
    zebra_count=None,
    zebra_opacity=None,
    zebra_direction=None,
    zebra_color_scheme=None,
    zebra_mapping_mode=None,
    pan_speed=None,
    rotate_speed=None,
    zoom_speed=None,
    deviation=None,
    angular_tolerance=None,
    edge_accuracy=None,
    default_color=None,
    default_edgecolor=None,
    ambient_intensity=None,
    direct_intensity=None,
    metalness=None,
    roughness=None,
    render_edges=None,
    render_normals=None,
    render_mates=None,
    render_joints=None,
    show_parent=None,
    show_locals=None,
    show_sketch_local=None,
    helper_scale=None,
    studio_environment=None,
    studio_env_intensity=None,
    studio_env_rotation=None,
    studio_background=None,
    studio_tone_mapping=None,
    studio_exposure=None,
    studio_shadow_intensity=None,
    studio_shadow_softness=None,
    studio_ao_intensity=None,
    studio_texture_mapping=None,
    studio_4k_env_maps=None,
    debug=None,
    timeit=None,
    cad_width=None,
    height=None,
): ...
def get_defaults(): ...
def get_default(
    key,
): ...
def reset_defaults(
    apply=True,
): ...
def set_viewer_config(
    axes=None,
    axes0=None,
    grid=None,
    center_grid=None,
    ortho=None,
    transparent=None,
    black_edges=None,
    explode=None,
    zoom=None,
    position=None,
    quaternion=None,
    target=None,
    default_edgecolor=None,
    default_opacity=None,
    ambient_intensity=None,
    direct_intensity=None,
    metalness=None,
    roughness=None,
    zoom_speed=None,
    pan_speed=None,
    rotate_speed=None,
    glass=None,
    tools=None,
    tree_width=None,
    theme=None,
    modifier_keys=None,
    collapse=None,
    reset_camera=None,
    states=None,
    tab=None,
    clip_slider_0=None,
    clip_slider_1=None,
    clip_slider_2=None,
    clip_normal_0=None,
    clip_normal_1=None,
    clip_normal_2=None,
    clip_intersection=None,
    clip_planes=None,
    clip_object_colors=None,
    zebra_count=None,
    zebra_opacity=None,
    zebra_direction=None,
    zebra_color_scheme=None,
    zebra_mapping_mode=None,
    studio_environment=None,
    studio_env_intensity=None,
    studio_env_rotation=None,
    studio_background=None,
    studio_tone_mapping=None,
    studio_exposure=None,
    studio_shadow_intensity=None,
    studio_shadow_softness=None,
    studio_ao_intensity=None,
    studio_texture_mapping=None,
    studio_4k_env_maps=None,
    analysis_tool=None,
    port=None,
    viewer=None,
): ...
def combined_config(): ...
def workspace_config(): ...
def status(
    debug=False,
): ...

# The transport-shaped names of `_HOST_ONLY`: importable, absent from
# `__all__`, and an ImportError at runtime under a host that lacks them.

# websocket hosts (ocp_vscode, ocp_viewer)
def get_port(): ...
def set_port(
    port,
    host="127.0.0.1",
): ...

# jupyter_cadquery
def close_viewer(
    title,
): ...
def close_viewers(): ...
def get_default_viewer(): ...
def get_user_defaults(): ...
def get_viewer(
    title=None,
): ...
def open_viewer(
    title=None,
    anchor="right",
    cad_width=800,
    tree_width=250,
    height=600,
    aspect_ratio=None,
    theme="browser",
    glass=True,
    tools=True,
    pinning=True,
    default=True,
): ...
def save_user_defaults(): ...
def set_default_viewer(
    title,
    anchor="right",
): ...
